apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
  namespace: my-jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-set
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
